# Generated by Django 5.1.6 on 2026-07-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
