# Generated by Django 5.1.6 on 2026-07-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Chef', 'Chef'), ('Waiter', 'Waiter'), ('Manager', 'Manager'), ('Cashier', 'Cashier')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20)),
                ('joining_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
