# Generated by Django 5.1.6 on 2026-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_time']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Seated', 'Seated'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20),
        ),
    ]
